name: Deploy Zola site to GitHub Pages

on:
  push:
    branches:
      - main # Change this if your default branch is named 'master'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # Important if you added your theme as a git submodule

      - name: Build Zola
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          BUILD_ONLY: false
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
